name: Deploy Playwright Report to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate report
        run: npx playwright test --reporter=html

      - name: Upload Playwright HTML Report
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report # Path to your generated report directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
